Test 1 proposal
RUB-EP1/ExercisesDataAnalysisWS2425 pull request #1
Opened 2024-10-21 11:11 UTC by marianstahl

FYI @mmikhasenko @IlyaSegal

2024-10-21 14:58 UTC, mmikhasenko commented
merged in main, and polished by running `pre-commit run -a`.
A few notes:
 - the functions that are exported (`export rbw`) one can call without the module name (no need for `DataAnalysisWS2425.rbw`)
 - in relation to that, I suggest to rename `gauss` - make it less general
 - `rbw` => `relativistic_breit_wigner`
- also, replaced `==` to `≈` (`\approx`) for floats

Could you please confirm that these test can be satisfied

2024-10-21 15:06 UTC, mmikhasenko requested changes

2024-10-21 15:06 UTC, mmikhasenko commented on tutorials/tutorial-01.md
> +1. `gauss(x; μ, σ, a)`, where `a` is an arbitrary normalization factor
suggest renaming to make to more specific and clear.
It does not have to be too short

2024-10-21 15:06 UTC, mmikhasenko commented on tutorials/tutorial-01.md
> +```
Suggest placing here a docstring that students can reuse

(chatgpt)

```
"""
    sample_rejection(f, n, support; nbins=1000)

Generates `n` samples using the rejection sampling method for a given function `f` over a specified `support` range.

# Arguments
- `f::Function`: The function to sample from.
- `n::Int`: The number of samples to generate.
- `support::Tuple{T, T}`: A tuple specifying the range `(a, b)` where the function `f` will be sampled.
- `nbins::Int`: Optional. The number of equidistant points in `support` to find the maximum of `f`. Default is `1000`.

# Returns
- An array of `n` samples generated from the distribution defined by `f`.

# Example
```julia
data = sample_rejection(cos, 1000, (0, pi); nbins=1000)
```
"""
```

2024-10-21 15:06 UTC, mmikhasenko commented on tutorials/tutorial-01.md
> +```
Replace to a docstring

2024-10-21 15:06 UTC, mmikhasenko commented on tutorials/tutorial-01.md
> +```
@DhruvanshuSan and students found this function already implemented in `Statistics.jl`

2024-10-22 07:29 UTC, marianstahl commented
Hi @mmikhasenko . Comments are implemented, please check again

2024-10-22 20:30 UTC, mmikhasenko approved these changes

2024-10-22 20:30 UTC, merged